spring:
  cloud:
    gateway:
      routes:
      - id: request-route
        uri: lb://trace-monitor-api
        predicates:
        - Path=/tracemonitor/request/{requestId}
        filters:
        - SetPath=/tracemonitor/request/{requestId}
      - id: get-all-request-route
        uri: lb://trace-monitor-api
        predicates:
        - Path=/tracemonitor/request
        filters:
        - SetPath=/tracemonitor/request
        - AddResponseHeader=Access-Control-Allow-Origin, *
      - id: event-route
        uri: lb://event-inbound-processor
        predicates:
        - Path=/event-inbound/event
        filters:
        - SetPath=/event-inbound/event
      - id: get-all-request-route
        uri: lb://trace-monitor-api
        predicates:
        - Path=/cb
        filters:
        - Hystrix=fallbackcmd
        - SetPath=/tracemonitor/request/delay
management.endpoints.web.exposure.include: hystrix.stream

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
