spring:
  cloud:
    gateway:
      routes:
      - id: request-route
        uri: lb://trace-monitor-api/tracemonitor/request
        predicates:
        - Path=/tracemonitor/request
      - id: event-route
        uri: lb://event-inbound-processor/event-inbound/event
        predicates:
        - Path=/event-inbound/event