spring:
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://demo-mysql-mysql.middleware.svc.cluster.local:3306/zipkinTest?createDatabaseIfNotExist=true
    username: root
    password: changeme
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql
server:
  port: 9411