spring:
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://mysql.atticspace.svc.cluster.local:3306/zipkinStage?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql
server:
  port: 9411