kind: Service
apiVersion: v1
metadata:
  name: mc-config-service
  namespace: middleware
  labels:
    prometheus: magecoffee
spec:
  selector:
    app: mc-config-server
  type: ClusterIP
  ports:
  - protocol: restapi
    port: 8888
    targetPort: 8888