apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mc-config-server
  namespace: development
spec:
  selector:
    matchLabels:
      app: mc-config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-config-server
    spec:
      imagePullSecrets:
      - name: image-registry-secret
      containers:
      - name: mc-config-server
        imagePullPolicy: Always
        image: registry-vpc.cn-beijing.aliyuncs.com/megacoffee/config-server:latest
        ports:
        - containerPort: 8888
          name: restapi
        env:
        - name: SPRING_APPLICATION_NAME
          value: "config-server"
        - name: MANAGEMENT_SECURITY_ENABLED
          value: "false"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
        - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_PREFER-IP
          value: "true"
        - name: SPRING_BOOT_ADMIN_CLIENT_URL
          value: "http://ms-admin-svc.development.svc.cluster.local:8080"
#        - name:
#        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
#          value: "http://eureka-dev-svc.development.svc.cluster.local:8761/eureka"
#        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES
#          value: "kafka-zookeeper-0.kafka-zookeeper-headless.kafka.svc.cluster.local:2181,kafka-zookeeper-1.kafka-zookeeper-headless.kafka.svc.cluster.local:2181,kafka-zookeeper-2.kafka-zookeeper-headless.kafka.svc.cluster.local:2181"
#        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
#          value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.middleware.svc.cluster.local:9092"
        - name: SERVER_PORT
          value: "8888"
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          valueFrom:
            configMapKeyRef:
              name: mc-config-server-config
              key: github.uri
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mc-secret
              key: username
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mc-secret
              key: password